

use customer_behavior;
select * from customer;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue from customer group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customer where discount_applied='Yes' and purchase_amount>( select avg(purchase_amount) from customer );

--  Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as avg_rating from customer group by item_purchased order by avg_rating desc  limit 5; 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
  select shipping_type,round(avg(purchase_amount),2) as avg_amount_spend from customer where shipping_type in ('standard','express') group by shipping_type;
 
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_customer,round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_revenue from customer group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,	round((count(*)*100/(select count(*) from customer c2 where c2.item_purchased=c1.item_purchased )),2) as discount_rate from customer c1 where discount_applied='Yes' group by item_purchased  order by discount_rate desc limit 5;
select item_purchased , round((sum(case when discount_applied='Yes' then 1 else 0 End)/count(*)*100),2) as discount_rate from customer group by item_purchased order by discount_rate desc limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select if(previous_purchases=1,'New',if(previous_purchases<=10,'returning','loyal')) as customer_segmentation,count(*) from customer group by customer_segmentation;

select 
	case
		when previous_purchases=1 then 'new'
        when previous_purchases<=10 then 'returning'
        else 'loyal'
    end as customer_segmentation, count(*) as no_of_customer from customer group by customer_segmentation;
    
-- Q8. What are the top 3 most purchased products within each category? 
with count_item as (
	select category,item_purchased,count(customer_id) as total_count,
    row_number() over (partition by category order by count(customer_id) desc) as item_rank from customer
    group by category,item_purchased)
    
select item_rank,category,item_purchased,total_count from count_item where item_rank<=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyer from customer where previous_purchases>5 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as total_revenue   from customer group by age_group order by total_revenue desc;
 

